### ISSUE TITLE
Add @milindmantri to the team

### ISSUE THREAD

**Issue by dostiharise** [alvyl/alvyl-consulting-website#42]
@milindmantri, please add yourself to the team here and in "alvyl/alvyl-consulting-profile".

Thanks.

**Comment by milindmantri** [comment]
#46 does this.

**Comment by milindmantri** [comment]
#46 does this here.
https://github.com/alvyl/alvyl-consulting-profile/pull/18 for "alvyl/alvyl-consulting-profile"

Closing this for now.
